name: Git Secrets Scan

on:
  push:
    branches:
      - '*'

jobs:
  git-secrets-scan:
    name: Git Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Git Secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          make install
        # Output: Git Secrets installed successfully.

      - name: Register AWS Secrets
        run: git secrets --register-aws
        # Output: AWS secrets registered.

      - name: Scan Repository
        run: git secrets --scan -r
        # Output: Git secrets scan completed.
