name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets_temp
        cd /tmp/git-secrets_temp
    - name: Check if directory exists
      run: |
        if [ -d "/tmp/git-secrets_temp/.git" ]; then
          rm -rf /tmp/git-secrets_temp
        fi
    - name: Clone git-secrets repository
      run: |
        git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets_temp
    - name: Install git-secrets
      run: |
        cd /tmp/git-secrets_temp
        make install PREFIX=/tmp/git-secrets_temp/install
    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --register-aws --global
    - name: Set the output in bash
      id: step_one
      run: |
        touch GITHUB_OUTPUT.txt
        ls
        /tmp/git-secrets_temp/install/bin/git-secrets --scan &> GITHUB_OUTPUT.txt || true
        ls
        pwd
        cat GITHUB_OUTPUT.txt
    - name: Send output to Slack
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        SLACK_FILE_UPLOAD: GITHUB_OUTPUT.txt
        args: |
          The following secrets were found:
          ```
          $(cat GITHUB_OUTPUT.txt)

    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: GITHUB_OUTPUT.txt
          channels: ${{ secrets.SLACK_CHANNEL_ID }}

