name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  secret_scan:
    name: Scan for Git Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets
        cd /tmp/git-secrets

    - name: Download git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git .
        make install PREFIX=/tmp/git-secrets/install

    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets/install/bin/git-secrets --register-aws --global

    - name: Scan for Git Secrets
      run: |
        /tmp/git-secrets/install/bin/git-secrets --scan

    - name: Revert changes in repository
      run: |
        git reset --hard HEAD

    - name: Clean up temporary directory
      run: |
        rm -rf /tmp/git-secrets
