name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  secret_scan:
    name: Scan for Git Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets_temp
        cd /tmp/git-secrets_temp

    - name: Check if directory exists
      run: |
        if [ -d "/tmp/git-secrets_temp/.git" ]; then
          rm -rf /tmp/git-secrets_temp
        fi

    - name: Clone git-secrets repository
      run: |
        git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets_temp

    - name: Install git-secrets
      run: |
        cd /tmp/git-secrets_temp
        make install PREFIX=/tmp/git-secrets_temp/install

    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --register-aws --global

    - name: Scan for Git Secrets
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --scan

    - name: Revert changes in repository
      run: |
        git reset --hard HEAD

    - name: Move to final directory
      run: |
        mv /tmp/git-secrets_temp /tmp/git-secrets

    - name: Clean up temporary directory
      run: |
        rm -rf /tmp/git-secrets
