name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  secret_scan:
    name: Scan for Git Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download git-secrets
      run: |
        wget -O /tmp/git-secrets.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
        tar -xvf /tmp/git-secrets.tar.gz -C /tmp/
        cd /tmp/git-secrets-1.3.0 && sudo make install PREFIX=/home/ubuntu
      
    - name: Add git secrets patterns for AWS provider
      run: /home/ubuntu/bin/git secrets --register-aws --global

    - name: Scan for Git Secrets
      run: /home/ubuntu/bin/git secrets --scan
