name: Secret Scanning
on:
  push:
    branches:
      - '*'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.scansecrets.outputs.scan_output }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets_temp
        cd /tmp/git-secrets_temp
    - name: Check if directory exists
      run: |
        if [ -d "/tmp/git-secrets_temp/.git" ]; then
          rm -rf /tmp/git-secrets_temp
        fi
    - name: Clone git-secrets repository
      run: |
        git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets_temp
    - name: Install git-secrets
      run: |
        cd /tmp/git-secrets_temp
        make install PREFIX=/tmp/git-secrets_temp/install

    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --register-aws --global
    - name: Scan for Git Secrets
      id: scansecrets
      run: > 
        /tmp/git-secrets_temp/install/bin/git-secrets --scan -r || true >> output.log
        echo "scan_output=$(cat output.log)"  >> "$GITHUB_OUTPUT"

    - name: Slack Notification
      if: ${{ always() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: ${{ steps.scan-secrets.outputs.scan_output }}
        SLACK_TITLE: Post Title
  job2:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
