name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.scansecrets.outputs.test }}  # Changed from 'test' to 'output1'
      output2: ${{ steps.scansecrets2.outputs.multi_line_output }}  # Changed from 'multi_line_output' to 'output2'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets_temp
        cd /tmp/git-secrets_temp
    - name: Check if directory exists
      run: |
        if [ -d "/tmp/git-secrets_temp/.git" ]; then
          rm -rf /tmp/git-secrets_temp
        fi
    - name: Clone git-secrets repository
      run: |
        git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets_temp
    - name: Install git-secrets
      run: |
        cd /tmp/git-secrets_temp
        make install PREFIX=/tmp/git-secrets_temp/install
    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --register-aws --global
    - name: Scan for Git Secrets
      id: scansecrets
      run: echo "test=world" >> $GITHUB_OUTPUT
    - name: Print Multi-line Output
      id: scansecrets2
      run: |
        output=$(/tmp/git-secrets_temp/install/bin/git-secrets --scan -r) || true
        echo "::set-output name=multi_line_output::$output"  # Added $ to capture output
    - name: Print output
      run: echo ${{ steps.scansecrets2.outputs.multi_line_output }}  # Corrected to use 'output2' instead of 'multi_line_output'
    - name: create string
      run: |
          MY_STRING=$(/tmp/git-secrets_temp/install/bin/git-secrets --scan -r) || true
          echo "MY_STRING<<EOF" >> $GITHUB_ENV
          echo "$MY_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      id: my_string
    - name: display string
      run: |
          echo "The string is: ${{ env.MY_STRING }}"
    - name: create string1
      run: |
          MY_STRING1=$(/tmp/git-secrets_temp/install/bin/git-secrets --scan -r) || true
          echo "::set-output name=content::$MY_STRING1"
      id: my_string1
    - name: display string1
      run: |
          echo "The string is: ${{ steps.my_string1.outputs.content }}"



  job2:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}  # Changed from 'test' to 'output1'
          OUTPUT2: ${{needs.job1.outputs.output2}}  # Changed from 'multi_line_output' to 'output2'
        run: echo "$OUTPUT1 $OUTPUT2"
