name: Secret Scanning

on:
  push:
    branches:
      - '*'

jobs:
  secret_scan:
    name: Scan for Git Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up temporary directory
      run: |
        mkdir -p /tmp/git-secrets_temp
        cd /tmp/git-secrets_temp

    - name: Check if directory exists
      run: |
        if [ -d "/tmp/git-secrets_temp/.git" ]; then
          rm -rf /tmp/git-secrets_temp
        fi

    - name: Clone git-secrets repository
      run: |
        git clone https://github.com/awslabs/git-secrets.git /tmp/git-secrets_temp

    - name: Install git-secrets
      run: |
        cd /tmp/git-secrets_temp
        make install PREFIX=/tmp/git-secrets_temp/install

    - name: Add git secrets patterns for AWS provider
      run: |
        /tmp/git-secrets_temp/install/bin/git-secrets --register-aws --global

    - name: Scan for Git Secrets
      run: |
        set +e
        scan_output=$(/tmp/git-secrets_temp/install/bin/git-secrets --scan 2>&1)
        scan_exit_code=$?
        if [ $scan_exit_code -ne 0 ]; then
          echo "::error::Git secrets scan failed with exit code $scan_exit_code"
          echo "::error::$scan_output"
          echo "::set-output name=scan_error::$scan_output"
        elif [[ $scan_output ]]; then
          echo "::warning::Git secrets found potential patterns"
          echo "::set-output name=scan_warning::$scan_output"
        else
          echo "Git secrets scan passed"
        fi

    - name: Notify Slack if scan failed
      if: steps.secret_scan.outcome != 'success' || steps.secret_scan.outputs.scan_error != ''
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        entryPoint: post
        args: |
          {"text": "Secret scanning completed for the repository.\nStatus: ${{ job.status }}\nConclusion: ${{ job.conclusion }}\nError: ${{ steps.secret_scan.outputs.scan_error }}\nWarning: ${{ steps.secret_scan.outputs.scan_warning }}" 

